version: '3.8'
services:
  recipe:
    image: ${IMAGE}
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - maria_db_recipe
    deploy:
      replicas: 1
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=recipe_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_vol: