spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe?createDatabaseIfNotExist=true
    username: postgres
    password: local
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      order_updates: true
      batch_versioned_data: true
      jdbc:
      batch_size: 1000
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
        metadata_builder_contributor: com.example.recipe.config.SqlFunctionsRegistry
